version: "3"

services:
  ui:
    build: ./ui
    command: npm -- start
    volumes:
     - ./ui:/app
     - /app/node_modules
    ports:
      - "80:80"
      - "5858:5858"
      - "4200:4200"
      - "8081:8081"
    networks:
      - ui-tier
      - service-tier

  api:
    build: ./api
    command: python app.py
    volumes:
      - ./api:/app
    ports:
      - "8080:8080"
    networks:
      - service-tier
      - db-tier

  db:
    image: postgres:9.4
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - ./sql:/docker-entrypoint-initdb.d/
    networks:
      - db-tier

volumes:
  db-data:

networks:
  ui-tier:
  service-tier:
  db-tier:
