version: "3"

services:
  ui:
    build: ./ui
    container_name: ui
    command: npm -- start
    volumes:
     - ./ui:/app
     - /app/node_modules
    ports:
      - "8080:80"
    networks:
      - frontend
    links:
      - api

  api:
    build: ./api
    container_name: api
    command: python app.py
    volumes:
      - ./api:/app
    ports:
      - "8081:80"
    networks:
      - frontend
      - backend

  db:
    image: postgres:9.4
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - ./sql:/docker-entrypoint-initdb.d/
    networks:
      - backend

volumes:
  db-data:

networks:
  frontend:
  backend:
